# Generated by Django 5.0.2 on 2024-02-27 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 17, 10, 508987)),
        ),
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
