# Generated by Django 5.0.2 on 2024-02-27 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_api', '0002_alter_photography_date_alter_photography_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[(0, 'N/A'), (1, 'Nebula'), (2, 'Star'), (3, 'Galaxy'), (4, 'Planet')], default='Na', max_length=80),
        ),
        migrations.AlterField(
            model_name='photography',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 10, 56, 881260)),
        ),
    ]
