# Generated by Django 5.0.2 on 2024-02-27 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_api', '0003_alter_photography_category_alter_photography_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Nebula'), (2, 'Star'), (3, 'Galaxy'), (4, 'Planet')], default=0),
        ),
        migrations.AlterField(
            model_name='photography',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 13, 40, 729703)),
        ),
    ]
