# Generated by Django 5.0.2 on 2024-02-27 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_api', '0007_alter_photography_category_alter_photography_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('N_a', 'N/A'), ('Neb', 'Nebula'), ('Sta', 'Star'), ('Gal', 'Galaxy'), ('Pla', 'Planet')], default='Na', max_length=3),
        ),
        migrations.AlterField(
            model_name='photography',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 50, 10, 673433)),
        ),
    ]
