# Generated by Django 5.0.2 on 2024-02-27 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_api', '0008_alter_photography_category_alter_photography_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (1, ''), (2, 'Star'), (3, 'Galaxy'), (4, 'Planet')], default=0),
        ),
        migrations.AlterField(
            model_name='photography',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 18, 7, 58, 955085)),
        ),
    ]
